version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong!Pass123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sqlserver-init:/docker-entrypoint-initdb.d
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &
        echo 'Esperando a que SQL Server esté listo...' &&
        until /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Strong!Pass123 -Q 'SELECT 1' &> /dev/null
        do
          sleep 2
        done &&
        echo 'SQL Server listo. Ejecutando scripts de inicialización...' &&
        for f in /docker-entrypoint-initdb.d/*.sql; do
          echo \"Ejecutando $f\" &&
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Strong!Pass123 -i $f
        done &&
        wait
      "

volumes:
  mysql_data:
  postgres_data:
  sqlserver_data:
